home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('home/', views.index, name='home'),
    path('register/', views.registration, name='registration'),
    path('login/', views.login, name='login'),
    path('saveUser/', views.saveUser, name='saveUser'),
    path('loginuser/', views.loginuser, name='loginuser'),
    path('index/',views.HomePage,name='index'),
    path('logout/',views.LogoutPage,name='logout'),
    path('userupdate/',views.userUpdate,name='userupdate'),
    path('updateinfo/',views.updatewon,name='updatewon'),
    path('updateeachuser/', views.updateeachuser, name='updateeachuser'),
    path('userupdateadmin/',views.userupdateadmin,name='userupdateadmin'),
    path('addproduct/',views.addproduct,name='addproduct'),
    path('saveproduct/',views.saveproduct,name='saveproduct'),
    path('productupdate/<int:item>',views.productupdate,name='productupdate'),
    path('viewproduct/<int:item>',views.viewproduct,name='viewproduct'),
    path('updateproduct/',views.updateproduct,name='updateproduct'),
    path('about/',views.about,name='about'),
    path('price/',views.price,name='price'),
    path('addnotice/',views.addnotice,name='addnotice'),
    path('savenotice/',views.savenotice,name='savenotice'),
    path('notice/',views.notice,name='notices'),
    path('services/',views.services,name='services'),
]

shqtc/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
]

home/models.py
from django.db import models
import os
class Userdetails(models.Model):
    user_id = models.IntegerField(unique=True)
    phone = models.IntegerField(unique=True,default=0)
    designation = models.CharField(max_length=150)
    organization = models.CharField(max_length=250)
    type = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    
class Productsdetails(models.Model):
    users_id = models.CharField(max_length=300)
    product_name = models.CharField(max_length=250,unique=True)
    organization_name = models.CharField(max_length=250)
    vendors_name = models.CharField(max_length=1000)
    p_type = models.CharField(max_length=50)
    issue_date = models.DateField()

class Productstatus(models.Model):
    product_id = models.IntegerField(unique=True)
    status = models.CharField(max_length=50)
    update_user = models.CharField(max_length=250)
    update_date = models.DateField()

class Notice(models.Model):
    notice_name = models.CharField(max_length=500)
    upload_date = models.DateField()
    file = models.FileField()
    def filename(self):
        return os.path.basename(self.file.name)

home/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect,HttpResponse
from django.template import loader
from django.contrib.auth.models import User 
from django.contrib.auth import authenticate, login as auth_login,logout
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required, user_passes_test
from home.models import Userdetails
from home.models import Productsdetails
from home.models import Productstatus
from home.models import Notice
from django.contrib import messages
from datetime import date
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.dateparse import parse_date 
from django.db import transaction, DatabaseError,IntegrityError
from django.views.generic.edit import FormView

def index(request):
  template = loader.get_template('index.html')
  return HttpResponse(template.render())

def registration(request):
  template = loader.get_template('registration.html')
  return HttpResponse(template.render())

def login(request):
  if(request.user.is_authenticated):
     return redirect('index')
  template = loader.get_template('login.html')
  return HttpResponse(template.render())

@csrf_exempt
def saveUser(request):
    if request.method == "POST":
       name = request.POST.get('name')
       mobile = request.POST.get('mobile')
       email = request.POST.get('email')
       password = request.POST.get('password')
       designation = request.POST.get('designation')
       organization = request.POST.get('organization')
       user = User.objects.create_user(username=email, email=email,password=password)
       user.first_name = name
       user.is_active = 0
       user.is_staff = 0
       user.is_superuser = 0
       try:
          user.save()
       except (IntegrityError,DatabaseError) as e:
          return HttpResponse (e)
       id_u = User.objects.get(email=email).pk
       userdetails = Userdetails()
       userdetails.user_id = id_u
       userdetails.phone = mobile
       userdetails.designation = designation
       userdetails.organization = organization
       try:
          userdetails.save()
       except (DatabaseError, IntegrityError) as e:
          return HttpResponse (e)
    return render(request,'login.html',{'m':'Information provided to SHQTC Team, After approval you can login'})

@login_required(login_url='login')
def HomePage(request):
   list = []
   if request.user.is_staff:
      pr_ids = Productstatus.objects.filter(status='NEW')
      for pr in pr_ids:
         pr_details = Productsdetails.objects.filter(id=pr.product_id).values()
         list.append(pr_details)
   else:
      listu = findproductidbyuid(request.user.id)
      for pr in range(len(listu)):
         pr_details = Productsdetails.objects.filter(id=listu[pr]).values()
         list.append(pr_details)
   context = {
         'list': list,
         }
   return render(request,'home.html',context)

@csrf_exempt
def loginuser(request):
   email = request.POST.get('email')
   password = request.POST.get('password')
   user = authenticate(username=email, password=password)
   m = ''
   list = []
   if user is not None:
      auth_login(request,user)
      return redirect('index')
   else:
      return HttpResponse ('username and password not matched')
  # return render(request, "login.html",{'m':m})

def LogoutPage(request):
    logout(request)
    return redirect('login')

@user_passes_test(lambda u: u.is_superuser,login_url='login')
def userUpdate(request):
    if request.method == "POST":
       id = request.POST.get('id')
       staff = request.POST.get('staff_d')
       isactive = request.POST.get('active_d')
       staffornot = 0
       activeornot = 0
       if(staff == 'True'):
          staffornot = 1
       if(isactive == 'True'):
          activeornot = 1
       
       #print(staff)
       user = User.objects.get(id=id)
       user.is_active = activeornot
       user.is_staff = staffornot
       user.save()
    list = []
    users = User.objects.all()
    for user in users:
       if(user.username != 'admin'):
         user_info = User.objects.filter(username=user.username).values()
         list.append(user_info)
    context = {
            'list': list,
            }
    return render (request,'userupdate.html',context)

@user_passes_test(lambda u: u.is_superuser,login_url='login')
def userupdateadmin(request):
    if request.method == "POST":
       id = request.POST.get('id')
       staff = request.GET['staff_d']
       print(staff)
    return HttpResponse('got')

@login_required(login_url='login')
def updatewon(request):
   if request.user.is_authenticated:
         user = request.user
         user_info = User.objects.get(username=user)
         username = user_info.email
         name = user_info.get_full_name
         info = user_info.is_staff
         ids = user_info.pk
         userdetails = Userdetails.objects.filter(user_id=ids).values()
         context = {
            'userdetails': userdetails,
            'username': username,
            'name': name
            }
   return render (request,'updatewon.html', context)

@csrf_exempt
def updateeachuser(request):
   current_user = request.user
   if request.method == "POST":
      name = request.POST.get('name')
      mobile = request.POST.get('mobile')
      email = request.POST.get('email')
      password = request.POST.get('password')
      designation = request.POST.get('designation')
      organization = request.POST.get('organization')
      user = User.objects.get(id=current_user.id)
      user.first_name = name
      user.email = email
      if len(password) > 1 :
        user.set_password(password)
      user.save()
      Userdetails.objects.filter(user_id=current_user.id).update(designation=designation, organization = organization, phone = mobile)
      auth_login(request,user)
      messages.info(request, 'Your Profile has been updated')
   return redirect('index')

@staff_member_required
def addproduct(request):
   return render (request,'addproduct.html')

@csrf_exempt
def saveproduct(request):
   if request.method == "POST":
       name = request.POST.get('product_name')
       organization = request.POST.get('organization')
       vendor = request.POST.get('vendor')
       ptype = request.POST.get('p_type')
       issue_date = request.POST.get('issue_date')
       product = Productsdetails()
       product.product_name = name
       product.organization_name = organization
       product.vendors_name = vendor
       product.p_type = ptype
       product.issue_date = parse_date(issue_date)
       try:
          product.save()
       except DatabaseError as e:
          return render(request, "home.html",{'m':e})
       id = Productsdetails.objects.get(product_name=name).pk
       
       productstatus = Productstatus()
       productstatus.product_id = id
       productstatus.status = 'NEW'
       productstatus.update_user = request.user
       productstatus.update_date =  date.today()
       try:
          productstatus.save()
       except DatabaseError as e:
          return render(request, "home.html",{'m':e})
       return render(request, "home.html",{'m':'Product added to database'})
@staff_member_required  
def productupdate(request,item):
   if request.method == "GET":
      pass
   else:
      return redirect('index')
   pr_details = Productsdetails.objects.filter(id=item)
   pr_status = Productstatus.objects.filter(product_id=item)
   P_name = ''
   status = ''
   users_id = ''
   update_user = ''
   update_date = ''
   for pr in pr_details:
      p_id = pr.pk
      P_name = pr.product_name
      users_id = pr.users_id
   user_list = []
   if(len(users_id)>1):
      user_array = users_id.split('|')
      for i in range(len(user_array)-1):
         user_e = User.objects.filter(id=user_array[i])
         for e in user_e:
            user_list.append(e.username)
   print(user_list)
   
   for pr in pr_status:
      status = pr.status
      update_user = pr.update_user
      update_date = pr.update_date
   users = User.objects.filter(is_active=True,is_staff=False)
   context = {
            'p_id': p_id,
            'p_name': P_name,
            'status': status,
            'update_user': update_user,
            'update_date': update_date,
            'users':users,
            'users_list':user_list,
            }
   return render(request, "productupdate.html",context)

@csrf_exempt
def updateproduct(request):
   user = request.user.username
   if request.method == 'POST':
      id = request.POST.get('id')
      status = request.POST.get('status')
      productstatus = Productstatus.objects.get(product_id=id)
      productstatus.product_id = id
      productstatus.status = status
      productstatus.update_user = user
      productstatus.update_date =  date.today()
      try:
          productstatus.save()
      except DatabaseError as e:
         return HttpResponse('not updated')
      print(status)
      users = request.POST.getlist('users')
      users_id = ''
      pr_details = Productsdetails.objects.get(id=id)
      for user_name in users:
         user_id = User.objects.get(username=user_name).pk
         users_id = users_id+str(user_id)+'|'
      pr_details.users_id = users_id
      try:
          pr_details.save()
      except DatabaseError as e:
         return HttpResponse('not updated')
   return redirect('productupdate',item=id)

def findproductidbyuid(id):
   listu = []
   pr_details = Productsdetails.objects.all() 
   for pr in pr_details:
      users_l = pr.users_id.split('|')
      for i in range(len(users_l)-1):
         if id == int(users_l[i]):
            listu.append(pr.pk)
   return listu
@login_required
def viewproduct(request,item):
   if request.method == "GET":
      if idinproduct(request.user.id,item):
         pass
      else:
         return redirect('index')
   else:
      return redirect('index')
   pr_details = Productsdetails.objects.filter(id=item)

home/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About SHQTC-BCC</title>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static '/assets/img/bcc_logo.png' %} ">
  <meta content="" name="description">
  <meta content="" name="keywords">
  
  <!-- Favicons -->
  <link href="{% static '/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static '/assets/vendor/aos/aos.css' %}" rel="stylesheet">

  <link href="{% static '/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  
  

  <!-- Template Main CSS File -->
  <link href="{% static '/assets/css/style.css' %}" rel="stylesheet">

  <!-- from main SQTC-->
  <link href="{% static '/css/style.css' %}" rel="stylesheet">
</head>
<body>
    <div class="main-body">

        <section id="topbar" class="d-flex align-items-center">
            <div class="container d-flex justify-content-center justify-content-md-between">
              <div class="contact-info d-flex align-items-center">
                <i class="bi bi-envelope d-flex align-items-center"><a href="SQTC@bcc.gov.bd">SQTC@bcc.gov.bd</a></i>
                <i class="bi bi-phone d-flex align-items-center ms-4"><span>+880 1713-118860</span></i>
              </div>
              <div class="social-links d-none d-md-flex align-items-center">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
              </div>
            </div>
          </section>
        

          <header id="header" class="d-flex align-items-center">
            <div class="container d-flex align-items-center justify-content-between">
        
              <h1 class="logo"><a href="/home">SHQTC<span>.</span></a></h1>
              <!-- Uncomment below if you prefer to use an image logo -->
              <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt=""></a>-->
        
              <nav id="navbar" class="navbar">
                <ul>
                  <li><a class="nav-link scrollto" href="/home">HOME</a></li>
                  <li><a class="nav-link scrollto active" href="/about">ABOUT</a></li>
                  <li><a class="nav-link scrollto " href="/price">PRICING</a></li>
                  <li><a class="nav-link scrollto" href="/notice">NOTICE</a></li>
                  <li class="dropdown"><a href="/services"><span>SERVICES</span> <i class="bi bi-chevron-down"></i></a>
                    <ul>
                      <li><a href="/services/#mobile_app">MOBILE APPS TESTING</a></li>
                      <li class="dropdown"><a href="/services/#regress_test"><span>REGRESSION TESTING</span> <i class="bi bi-chevron-right"></i></a>
                        <ul>
                          <li><a href="/services/#automated_ui">Automated UI Testing</a></li>
                          <li><a href="/services/#riskbased">Risk based analysis</a></li>
                          <li><a href="/services/#dependency_testing">Dependency analysis</a></li>
                        </ul>
                      </li>
                      <li><a href="/services/#performance_testing">PERFORMANCE TESTING</a></li>
                      <li><a href="/services/#functional_testing">FUNCTIONAL TESTING</a></li>
                    </ul>
                  </li>
                  
                  <li><a class="nav-link scrollto" href="/login">LOGIN</a></li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
              </nav><!-- .navbar -->
        
            </div>
          </header><!-- End Header -->
          <!--Body part-1-->
          <div class="body-part-about">
            <div class="bp-1-content">
                <!-- ======= Hero Section ======= -->
                <section class="d-flex align-items-center">
                    <div class="container" data-aos="zoom-out" data-aos-delay="100" style="margin-left: 20px; margin-right: 20px;">
                    <h1>About BCC</span></h1>
                    <p style="  text-align: justify;
                    text-justify: inter-word;">
                      Bangladesh Computer Council (BCC) is a statutory body under the Ministry of Posts, Telecommunications and Information Technology, Government of Bangladesh (GOB).  It was established by Act No IX of 1990 passed by the Parliament. The main activities are (not limited to) encouraging and providing support for ICT related activities, formulating national ICT strategy and policy, creating standards and specifications of ICT tools for government organizations according to their necessity, working for human resource development in ICT sector. It has also established National Data Center for hosting all the government websites, e-mail services and web applications. It is the only TIER – 3 certified Government Data Center in Bangladesh. In the near future, it will act as the only Gateway to access internet services for all of the government organizations. BCC is continuing ICT infrastructure development of government through several development projects/programs to facilitate access to government services from root level. In this vision, BCC has organized workshops, seminars, training on subjects related to ICT and has established throughout the country UISC (Union Information and Service Center).
                    </p>
                    </div>
                </section><!-- End Hero --> 
            </div>
            <div class="bp-1-slide">
                <!-- ======= Hero Section ======= -->
                <section class="d-flex align-items-center">
                  <div class="container" data-aos="zoom-out" data-aos-delay="100">
                  <h1>About SHQTC</span></h1>
                  <p style="  text-align: justify;
                  text-justify: inter-word;">
                    Software and Hardware Quality Testing and Certification(SHQTC) is one of the vital wings 
                    of Bangladesh Computer Council(BCC). Few years earlier there are number of incident happened
                    on number of govenrnment organization, the issues are - the software they used mostly 
                    developed by local vendors have many major issues like security, performance, accuracy. 
                    As a result Government understood necessity of a testing institute which can assure quality
                    product, the product which government can use without any security, performance and accuracy
                    issue. After that government gave responsibility to Bangladesh Computer Council(BCC), and BCC 
                    under Software Quality Testing and Certification(SQTC) project developed highly qualified institute
                    of testing Software. After goodwill in producing quality product hardware part are added to 
                    Software Quality Testing and Certification(SQTC). Later it is named Software and Hardware Quality Testing and Certification(SHQTC).
                    In last few years this SHQTC delivered many software as well as hardware. 
                  </p>
                  </div>
            </div>
          </div>
          
    
  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-newsletter">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <h4>Join Our Newsletter</h4>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>CONTACT INFO<span>.</span></h3>
            <p>
              Director,SQTC <br>
              Bangladesh Computer Council<br>
              E-14/X,ICT Tower, Agargaon<br>
              Sher e Bangla Nagar, Dhaka-1207<br>
              <strong>Phone:</strong> +880 1713-118860<br>
              <strong>Email:</strong> sqtc@bcc.gov.bd<br>
            </p>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>SITE MAP</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="/home">HOME</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="/about">ABOUT</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="/price">PRICING</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="/notice">NOTICE</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="/services/#mobile_app">MOBILE APPS TESTING</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="/services/#regress_test">REGRESSION TESTING</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="/services/#performance_testing">PERFORMANCE TESTING</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="/services/#functional_testing">FUNCTIONAL TESTING</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Social Networks</h4>
            <p></p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container py-4">
      <div class="copyright">
        &copy; Copyright <strong><span>SQTC</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/bizland-bootstrap-business-template/ -->
        Designed by <a href="">SQTC TEAM@RAZU_SHARIF</a>
      </div>
    </div>
  </footer><!-- End Footer -->
    <!--End of body--> 
    </div>
    
    <!-- Vendor JS Files -->
    
    <script src="{% static '/assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static '/assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static '/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static '/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static '/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static '/assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
    <script src="{% static '/assets/vendor/php-email-form/validate.js' %}"></script>


  <!-- Template Main JS File -->
  <script src="{% static '/assets/js/main.js' %}"></script>
</body>
</html>

home/templates/addnotice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SHQTC-BCC</title>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static '/assets/img/bcc_logo.png' %} ">
  <meta content="" name="description">
  <meta content="" name="keywords">
  
  <!-- Favicons -->
  
  <link href="{% static '/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static '/assets/vendor/aos/aos.css' %}" rel="stylesheet">

  <link href="{% static '/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  
  

  <!-- Template Main CSS File -->
  <link href="{% static '/assets/css/style.css' %}" rel="stylesheet">

  <!-- from main SQTC-->
  <link href="{% static '/css/style.css' %}" rel="stylesheet">
</head>
<body>
    <div class="main-body">

        <section id="topbar" class="d-flex align-items-center">
            <div class="container d-flex justify-content-center justify-content-md-between">
              <div class="contact-info d-flex align-items-center">
                <i class="bi bi-envelope d-flex align-items-center"><a href="/home">SHQTC WEBSITE</a></i>
                <i class="bi bi-phone d-flex align-items-center ms-4"><span>+880 1713-118860</span></i>
              </div>
              <div class="social-links d-none d-md-flex align-items-center">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
              </div>
            </div>
          </section>
 
  <!-- ======= Footer ======= -->
  <footer id="footer">
    
    <section >
      <h3 style="margin-bottom: 20px; text-align: center;">{{m}}</h3>
      <form action="{% url 'savenotice'%}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p style="margin-left: 20px;">
          <label for="id_notice_name">Notice name:</label>
          <input type="text" name="notice_name" maxlength="500" class="form-control" required id="id_notice_name">
          
        </p>
        <p style="margin-left: 20px;">
          <label for="id_docfile">File:</label>
          <input class="form-control" id="id_docfile" type="file" name="docfile"/>
        </p>
                <div class="px-5 py-2">
                  <button type="submit" class="btn btn-primary btn-lg" onclick="productValidate()">ADD</button>
                </div>
              
    </form>
  </section>

  <div class="container py-4">
    <div class="copyright">
      &copy; Copyright <strong><span>SQTC</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/bizland-bootstrap-business-template/ -->
      Designed by <a href="">SQTC TEAM@RAZU_SHARIF</a>
  </div>
</footer><!-- End Footer -->
  <!--End of body--> 
  </div>
    <!-- Vendor JS Files -->
    
    <script src="{% static '/assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static '/assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static '/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static '/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static '/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static '/assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
    <script src="{% static '/assets/vendor/php-email-form/validate.js' %}"></script>


  <!-- Template Main JS File -->
  <script src="{% static '/assets/js/main.js' %}"></script>
  <script type="text/javascript" src="{% static '/js/rs.js' %}"></script>
</body>
</html>

home/templates/saveuser.html
hello {{m}}
{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}